### ISSUE TITLE
[Bug]: edk2-pytool-library package does not declare supported Python versions

### ISSUE THREAD

**Issue by kondalgithub** [tianocore/edk2-pytool-library#213] opened 2022-12-04 21:33 UTC
### Contact Details

kondal.r.purma@intel.com

### Describe the Bug

edk2-pytool-library not defined Python version required to install the package in setup.py.
Users might successfully installs the package in any Python 3.x versions and expect to work.

### Reproduction steps

1.Install Python 3.8
2.Install edk2-pytool-extentions
3.stuart_ci_build command to build/run unit tests

### Expected behavior

Package should works as expected in any version of Python ,as we dont declare (min or all )supported Python versions.

### What Python version are you using?

Python 3.9

### Additional context

https://peps.python.org/pep-0440/

In setup along with classifier add the "python_requires" will fix the issue.
Ex:
Add
python_requires='>=3.9',
To setup.py (as we are not using pyproject.toml for package maintenance) .

**Comment by Javagedes** [comment] 2023-01-04 22:28
Hello @kondalgithub this is a duplicate of #201 

#223 resolves your issue, but I will be closing this now as it is a duplicate and being tracked in #201.

**Closed by Javagedes** 2023-01-04 22:28 UTC
Labels: bug
